[project]
name = "learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "keras>=3.15.1",
    "matplotlib>=3.11.2",
    "nltk>=3.10.3",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "tensorflow>=2.22.0rc0",
    "ultralytics>=8.4.161",
]
